[package]
name = "reaper"
version = "0.1.0"
authors = ["Peter Edge <edge.peterj@gmail.com>"]

[dependencies]
bio = "0.14.2"
rust-htslib = "0.13.0"
quick-error = "1.2.0"
clap = "2.26.2"
chrono = "0.4"
rand = "0.4"

[build-dependencies]
cc = "1.0"
