[package]
name = "longshot"
version = "0.2.0"
authors = ["Peter Edge <edge.peterj@gmail.com>"]

[dependencies]
bio = "0.17.0"
rust-htslib = "0.14.0"
quick-error = "1.2.0"
clap = "2.26.2"
chrono = "0.4"
rand = "0.4"
error-chain = "0.12.0"

[build-dependencies]
cc = "1.0"

#[profile.release]
#debug = true       # (u32 or bool) Include debug information (debug symbols).
